### PR TITLE
Address vhtml#11: Add ability to directly set innerHTML of a component using the `dangerouslySetInnerHTML` attribute.

### PR DESCRIPTION
**Pull request by pl12133**
Should take care of #11.

~~New Size: `630B`~~.
~~New Size: `624B`~~.
New Size: `615B`.

~~`50B` is kinda significant :cry: but I consider this a useful feature.~~

This was initially a `50B` increase in size but is now worked down to `35B` increase in size.

### CODE REVIEW

**Comment by paranoidjk** [comment]
+1 for this

**Comment by developit** [comment]
I think we can slim this down a bit without losing much functionality, but inlining the property name and skipping one of the conditionals:

```js
if (attrs && attrs.dangerouslySetInnerHTML) {
    s += attrs.dangerouslySetInnerHTML.__html;
}
```

**Comment by pl12133** [comment]
Good call on dropping the extra check, no need for `__html` to be valid to add it. I didn't inline the property because that seems to cost `1B` more than declaring `let setInnerHTMLAttr = 'dangerouslySetInnerHTML'`.

However I did find `4B` that can be cut out regardless (b8199d36) which should helps a little.

**Comment by ithinkihaveacat** [comment]
Aha, whoops maybe I should've looked here before implementing #17…

#17 does pass one test that this doesn't, though I'm not sure whether it "should" according to the spec. The test is:

```js
it('should support dangerouslySetInnerHTML (without __html)', () => {
  expect(
    <div dangerouslySetInnerHTML>foo</div>
  ).to.equal(
    '<div></div>'
  );
});
```

In this case, this PR returns `<div>undefined</div>`.

**Comment by developit** [comment]
@ithinkihaveacat - I'm going to merge Peter's here, since it's substantially smaller. I personally don't care what we return for the case of a boolean dangerouslySetInnerHTML value - since that actually throws in React most folks wouldn't be using it.

**Pull request merged**
